# 应用基本配置
spring.application.name=gp22023237-server
server.port=8088  # 服务端口号（可根据需要修改）
server.servlet.context-path=/

# 日志配置 - Mapper 接口执行SQL打印日志
logging.level.com.jameshao.gp22023237.mapper=debug
# 日志配置 Spring 框架详细日志（调试用，默认注释）
#logging.level.org.springframework=debug

# 数据库连接配置 MySQL 驱动
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# 替换localhost 为你的数据库IP，3306 为端口号，gp22023237 为数据库名
spring.datasource.url=jdbc:mysql://[数据库IP]:[数据库端口]/[数据库名称]?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
spring.datasource.username=[数据库用户名]  # 例如root
spring.datasource.password=[数据库密码]  # 填写你的数据库登录密码

# HikariCP 连接池配置
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.minimum-idle=5

# Redis 连接配置 Redis 服务器
spring.data.redis.host=[你的 Redis 服务器IP]  # 本地测试填 localhost
spring.data.redis.port=[你的 Redis 端口]  # 默认 6379
spring.data.redis.password=[你的 Redis 密码]  # 无密码则留空

# MyBatis-Plus 配置
mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.type-aliases-package=com.jameshao.gp22023237.po
mybatis-plus.configuration.lazy-loading-enabled=true
mybatis-plus.configration.aggressive-lazy-loading=true